export { allAreTrue } from "./functions/allAreTrue";
export { every, filter, find, findIndex, forEach, map, reduce, some } from "./functions/arrayPrototypes";
export { atLeastOneTrue } from "./functions/atLeastOneTrue";
export { commonsItemsBetweenArrays } from "./functions/commonsItemsBetweenArrays";
export { compose } from "./functions/compose";
export { createPropertyByOtherOne } from "./functions/createPropertyByOtherOne";
export { curry } from "./functions/curry";
export { debounce } from "./functions/debounce";
export { decide } from "./functions/decide";
export { equality } from "./functions/equality";
export { getPropertysValue } from "./functions/getPropertysValue";
export { identity } from'./functions/identity';
export { isEmpty } from "./functions/isEmpty";
export { isNotEmpty } from "./functions/isNotEmpty";
export { mergeObjects } from "./functions/mergeObjects";
export { removeItemFromArrayByIndex } from "./functions/removeItemFromArrayByIndex";
export { removeItemFromArrayByProp } from "./functions/removeItemFromArrayByProp";
export { returnUniqueArraysItems } from "./functions/returnUniqueArraysItems";
export { round } from "./functions/round";
export { setNewProperty } from "./functions/setNewProperty";

