export { allAreTrue } from "./functions/allAreTrue";
export { atLeastOneTrue } from "./functions/atLeastOneTrue";
export { commonsItemsBetweenArrays } from "./functions/commonsItemsBetweenArrays";
export { compose } from "./functions/compose";
export { debounce } from "./functions/debounce";
export { isEmpty } from "./functions/isEmpty";
export { isNotEmpty } from "./functions/isNotEmpty";
export { mergeObjects } from "./functions/mergeObjects";
export { returnUniqueArraysItems } from "./functions/returnUniqueArraysItems";

import createPropertyByOtherOneFn from "./functions/createPropertyByOtherOne";
import curry from "./functions/curry";
import decideFn from "./functions/decide";
import equalityFn from "./functions/equality";
import { everyFn, filterFn, findFn, findIndexFn, forEachFn, mapFn, reduceFn, someFn } from "./functions/arrayPrototypes";
import getPropertysValueFn from "./functions/getPropertysValue";
import identityFn from'./functions/identity';
import setNewPropertyFn from "./functions/setNewProperty";
import removeItemFromArrayByIndexFn from "./functions/removeItemFromArrayByIndex";
import removeItemFromArrayByPropFn from "./functions/removeItemFromArrayByProp";
import roundFn from "./functions/round";

export const createPropertyByOtherOne = curry(createPropertyByOtherOneFn);
export const decide = curry(decideFn);
export const equality = curry(equalityFn);
export const every = curry(everyFn);
export const filter = curry(filterFn);
export const find = curry(findFn);
export const findIndex = curry(findIndexFn);
export const forEach = curry(forEachFn);
export const getPropertysValue = curry(getPropertysValueFn);
export const identity = curry(identityFn);
export const map = curry(mapFn);
export const reduce = curry(reduceFn);
export const removeItemFromArrayByIndex = curry(removeItemFromArrayByIndexFn);
export const removeItemFromArrayByProp = curry(removeItemFromArrayByPropFn);
export const round = curry(roundFn);
export const setNewProperty = curry(setNewPropertyFn);
export const some = curry(someFn);
